spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql123
    url: jdbc:mysql://localhost/study?serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://192.168.44.200:3306/study?serverTimezone=Asia/Shanghai
    hikari:
      connection-timeout: 5000